import { HttpStatus } from 'server/common/http-status';

export enum CLIENT_ERROR_CODE {
  MAX_FILE_SIZE_EXCEEDED = 'MAX_FILE_SIZE_EXCEEDED',
  PHONE_NOT_FOUND = 'PHONE_NOT_FOUND',
  UNKNOWN_ERROR_PARSING_FILES = 'UNKNOWN_ERROR_PARSING_FILES',
}

export const CLIENT_ERROR_TO_HTTP_STATUS: {
  [key in CLIENT_ERROR_CODE]: HttpStatus;
} = {
  MAX_FILE_SIZE_EXCEEDED: HttpStatus.BAD_REQUEST,
  PHONE_NOT_FOUND: HttpStatus.NOT_FOUND,
  UNKNOWN_ERROR_PARSING_FILES: HttpStatus.INTERNAL_ERROR,
};
